version: '3.8'

services:
  db:
    image: mariadb:10.7.1
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - sample-db-vol:/var/lib/mysql
    networks:
      - sample-nw
  proxy:
    image: nginx
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sample-nw
    ports:
      - 80:80
    depends_on:
      - web
      - api
  web:
    image: sample/web:latest
    deploy:
      replicas: 3
    networks:
      - sample-nw
  api:
    image: sample/api:latest
    deploy:
      replicas: 2
    networks:
      - sample-nw
    depends_on:
      - db

volumes:
  sample-db-vol:
    external: true

networks:
  sample-nw:
