version: '3.8'

services:
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sample-nw
    ports:
      - 80:80
    depends_on:
      - web
      - api
  db:
    image: mariadb:10.7.1
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - sample-db-vol:/var/lib/mysql
    networks:
      - sample-nw
  web:
    build:
      context: web
    container_name: web
    networks:
      - sample-nw
  api:
    build:
      context: api
    container_name: api
    networks:
      - sample-nw
    depends_on:
      - db

volumes:
  sample-db-vol:
    external: true

networks:
  sample-nw:
    external: true
